/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login of a user
         * @description A user (username, password) will be authenticated; a jwt access token (5min expiry) and a refresh token will be returned.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description The User object to be authenticated */
            requestBody?: {
                content: {
                    "application/json": {
                        /** @example tester */
                        username?: string;
                        /**
                         * Format: password
                         * @example psiodjkÜsö93JKK=w8dj
                         */
                        password?: string;
                    };
                };
            };
            responses: {
                /** @description access and refresh tokens are created */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @description the accees JWT to be used to access
                             * @example eyJhbJ9.eyJuYW1lIjoibm4OTg0Mn0.kgR2dN1VsZ_1Vd8",
                             */
                            accessToken?: string;
                            /**
                             * @description refresh JWT
                             * @example eyIjshJ9.eyJOOksW1lIjdasdihg0Mn0.kgR2dNsda2d8",
                             */
                            refreshToken?: string;
                        };
                    };
                };
                /** @description Unauthorized; usually when no password was provided or when user is not registered or when password was incorrect */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @description error message
                             * @example Unauthorized
                             */
                            message?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** logout and destroy tokens; does not need bearer token */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description long living refresh token will be invalidated (short living access token might still live until expiry) */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["Token"];
                };
            };
            responses: {
                /** @description Invalidates the refresh token of a user */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh the access token using the refresh token */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description long living refresh token will be invalidated (short living access token might still live until expiry) */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["Token"];
                };
            };
            responses: {
                /** @description new access token */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @description new accees JWT to be used to access
                             * @example eyJhbJ9.eyJuYW1lIjoibm4OTg0Mn0.kgR2dN1VsZ_1Vd8",
                             */
                            accessToken?: string;
                            user?: {
                                /**
                                 * @description user name linked to this token
                                 * @example user@university.edu
                                 */
                                name?: string;
                                /**
                                 * @description generation timetamp
                                 * @example 1618390174
                                 */
                                iat?: number;
                                /**
                                 * @description expire timetamp
                                 * @example 1618390174
                                 */
                                exp?: number;
                            };
                        };
                    };
                };
                /** @description refresh token is invalid */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @description error message
                             * @example Unauthorized (invalid refresh token)
                             */
                            message?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read all time entries
         * @description Reads all time entries;
         *     read entries by date getAllByDate -> List of Time Entry of the given day;
         *     Read busy time getBusyTime -> Busy Time of the given day (in ms)
         */
        get: {
            parameters: {
                query?: {
                    /** @description Zeitstempel */
                    busy?: string;
                    /** @description Zeitstempel */
                    dt?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description All (or filtered) time entries */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TimeEntries"];
                    };
                };
                403: components["responses"]["UnauthorizedError"];
            };
        };
        put?: never;
        /**
         * Create new time entry
         * @description Create new time entry in system
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Time entry that we want to create */
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["TimeEntry"];
                };
            };
            responses: {
                /** @description New entry is created */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TimeEntry"];
                    };
                };
                403: components["responses"]["UnauthorizedError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entries/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get time entry with given ID */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID of time entry that we want to find */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description TimeEntry is found */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TimeEntries"];
                    };
                };
                403: components["responses"]["UnauthorizedError"];
            };
        };
        /** Update toggle with give ID */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID of time entry that we want to find */
                    id: string;
                };
                cookie?: never;
            };
            /** @description TimeEntry with new values of properties */
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["TimeEntry"];
                };
            };
            responses: {
                /** @description Toggle is updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TimeEntry"];
                    };
                };
                403: components["responses"]["UnauthorizedError"];
            };
        };
        post?: never;
        /** Delete time entry with given ID */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID of time entry that we want to find */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Time Entry is deleted */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TimeEntries"];
                    };
                };
                403: components["responses"]["UnauthorizedError"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entries/dump": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Backup data to file system
         * @description dump the mongodb to the local file system in order to be restored if needed
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description data dumped to file */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": Record<string, never>;
                    };
                };
                403: components["responses"]["UnauthorizedError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entries/dump/{modelType}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get time entrys from the set of last dumped data with given modelType */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Model Type reflected by mongoose model */
                    modelType: "User" | "StatsDay" | "Toggle" | "Properties" | "GeoFence" | "FailureDay" | "TimeEntry" | "GeoTracking";
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description TimeEntry is found */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": Record<string, never>[];
                    };
                };
                403: components["responses"]["UnauthorizedError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entries/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Restore data
         * @description Restore data from file which has been dumped by dump method
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description data sucessfully restored */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": Record<string, never>;
                    };
                };
                403: components["responses"]["UnauthorizedError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entries/backup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Backup data to database
         * @description backup data in an extra backup table
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description data saved to database */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": Record<string, never>;
                    };
                };
                403: components["responses"]["UnauthorizedError"];
                /** @description something went wrong... */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entries/error/evaluate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Evaluate time entries
         * @description Evaluate time entries on their consistency (completeness, order, etc.). As a result, the failure data will be put to an own document in mongodb. This data could be inquired by using the endpoint /api/entries/error/dates
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description data saved to database */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": Record<string, never>;
                    };
                };
                403: components["responses"]["UnauthorizedError"];
                /** @description something went wrong... */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entries/error/dates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Inquire the error time entries
         * @description Read all dates with error type that was written to database by endpoint /api/entries/error/evaluate
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description data saved to database */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * Format: date-time
                             * @example 2000-01-01T10:15:02.151Z
                             */
                            "error-date"?: string;
                            /**
                             * @description Type of the error - INCOMPLETE means that entries are missing and WRONG_ORDER means that the order of go and enter is not correctly booked
                             * @example INCOMPLETE or WRONG_ORDER
                             */
                            "error-type"?: string;
                        }[];
                    };
                };
                403: components["responses"]["UnauthorizedError"];
                /** @description something went wrong... */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entries/mark": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Mark the day as vacation or sick leave
         * @description Mark the day as vacation or sick leave (i.e. create two entries with this mark)
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Time entry that we want to create */
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["Mark-a-Day"];
                };
            };
            responses: {
                /** @description data sucessfully restored */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": Record<string, never>;
                    };
                };
                403: components["responses"]["UnauthorizedError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/geotrack": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Reads all geo tracking data for a given date
         * @description Reads all geo tracking data for a given date
         */
        get: {
            parameters: {
                query?: {
                    /**
                     * @description start date of the time range; format YYYY-MM-DD like 2020-03-09
                     * @example 2022-03-16T00:00:00.000Z
                     */
                    dateStart?: string;
                    /**
                     * @description end date of the time range; format YYYY-MM-DD like 2020-03-10
                     * @example 2022-03-17T00:00:00.000Z
                     */
                    dateEnd?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description delivered a valid result */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["GeotrackResponses"];
                    };
                };
                403: components["responses"]["UnauthorizedError"];
            };
        };
        put?: never;
        /**
         * Create new time entry from a geo tracking device like Hassio Mobil App or OwnTrack
         * @description Create new time entry from a geo tracking device like Hassio Mobil App or OwnTrack; the request body takes differen formats; internally they will be transformed to a internal general format before storing to database
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Time entry that we want to create using Geofencing */
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["Geotrack"];
                };
            };
            responses: {
                /** @description New entry is created */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["GeotrackResp"];
                    };
                };
                /** @description duplicate entry or encrypted data; does not change database and will be ignored */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description some data is missing */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                403: components["responses"]["UnauthorizedError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/geotrack/metadata": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * meta data about the track for the given time span
         * @description Returns som meta data about the track for the given time span
         */
        get: {
            parameters: {
                query?: {
                    /** @description start date of the time range; format YYYY-MM-DD like 2020-03-09 */
                    dateStart?: string;
                    /** @description end date of the time range; format YYYY-MM-DD like 2020-03-10 */
                    dateEnd?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description delivered a valid result */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["GeotrackMetaDataResponse"];
                    };
                };
                403: components["responses"]["UnauthorizedError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/toggles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all toggles in system */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Toggles"];
                    };
                };
                403: components["responses"]["UnauthorizedError"];
            };
        };
        put?: never;
        /**
         * Create new toggle in system
         * @description Create new toggle in system
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Toggle that we want to create */
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["Toggle"];
                };
            };
            responses: {
                /** @description New toggle is created */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Toggle"];
                    };
                };
                403: components["responses"]["UnauthorizedError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/toggles/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get toggle with given ID */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID of toggle that we want to find */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Toggle is found */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Toggle"];
                    };
                };
                403: components["responses"]["UnauthorizedError"];
            };
        };
        /** Update toggle with give ID */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID of toggle that we want to find */
                    id: string;
                };
                cookie?: never;
            };
            /** @description Toggle with new values of properties */
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["Toggle"];
                };
            };
            responses: {
                /** @description Toggle is updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Toggle"];
                    };
                };
                403: components["responses"]["UnauthorizedError"];
            };
        };
        post?: never;
        /** Delete toggle with given ID */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID of toggle that we want to find */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Toggle is deleted */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Toggle"];
                    };
                };
                403: components["responses"]["UnauthorizedError"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/toggles/name/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** read one toggle by its name */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Name of a toggle that we want to find */
                    name: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description All toggles status */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Toggle"];
                    };
                };
                403: components["responses"]["UnauthorizedError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/toggles/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Toggle status (currently onl) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description All toggles status */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            NOTIFICATION_SLACK?: boolean;
                        };
                    };
                };
                403: components["responses"]["UnauthorizedError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/properties": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read a all persisted properties */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Read a property by it's key. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Properties"];
                    };
                };
                403: components["responses"]["UnauthorizedError"];
                /** @description unable to read key-value pairs from database */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/properties/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read one persisted propertie's value */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Key of key-value pair */
                    key: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Read a property by it's key. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Properties"];
                    };
                };
                403: components["responses"]["UnauthorizedError"];
                /** @description Property for given key was not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description unable to read key-value pair from database */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        /** Create or update a property (key-value pair) */
        put: {
            parameters: {
                query: {
                    /** @description Value of key-value pair */
                    value: string;
                };
                header?: never;
                path: {
                    /** @description Key of key-value pair */
                    key: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description no body, please check http status code */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                403: components["responses"]["UnauthorizedError"];
                /** @description unable to store key-value pair */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        /** Delete a persisted property */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Key of key-value pair */
                    key: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description successfully deleted key-value pair */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                403: components["responses"]["UnauthorizedError"];
                /** @description Property for given key was not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description unable to delete key-value pair */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/geofences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read a all geofences */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Read a geofence by it's key. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Geofences"];
                    };
                };
                403: components["responses"]["UnauthorizedError"];
                /** @description unable to read geofences from database */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /** Creates a new geofence */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Geofence with new values of properties */
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["Geofence"];
                };
            };
            responses: {
                /** @description successfully created a new geofence */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                403: components["responses"]["UnauthorizedError"];
                /** @description unable to store key-value pair */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/geofences/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read one geofences by it's id */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description id of a geofence object */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Read a geofence by it's key. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Geofence"];
                    };
                };
                403: components["responses"]["UnauthorizedError"];
                /** @description Property for given key was not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description unable to read key-value pair from database */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        /** Update a geofence */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID of geofence */
                    id: string;
                };
                cookie?: never;
            };
            /** @description Geofence with new values of properties */
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["Geofence"];
                };
            };
            responses: {
                /** @description no body, please check http status code */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                403: components["responses"]["UnauthorizedError"];
                /** @description unable to store key-value pair */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        /** Delete a geofence */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description id of a geofence */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description successfully deleted geofence */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                403: components["responses"]["UnauthorizedError"];
                /** @description Property for given key was not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description unable to delete geofence */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read all users
         * @description Reads all time users from database;
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description All (or filtered) time entries */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UniqueUsers"];
                    };
                };
                403: components["responses"]["UnauthorizedError"];
            };
        };
        put?: never;
        /**
         * Create a new user
         * @description Create a new user with password. PWD will be stored encrypted
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description The User object to be created */
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["FullUser"];
                };
            };
            responses: {
                /** @description New user is created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"];
                    };
                };
                403: components["responses"]["UnauthorizedError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Loads an existing user by it's it
         * @description Loads an existing user by it's it
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description unique reference to user */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description A user from database */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UniqueUser"];
                    };
                };
                403: components["responses"]["UnauthorizedError"];
            };
        };
        /**
         * Updates an existing user
         * @description Updates an existing user
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description unique reference to user */
                    id: string;
                };
                cookie?: never;
            };
            /** @description The User object to be updated */
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            responses: {
                /** @description User sucessfully updated */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"];
                    };
                };
                403: components["responses"]["UnauthorizedError"];
                /** @description User (id) does not exist */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        /**
         * Delets an existing user incl. credentials
         * @description Deletes a new user with credentials
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description unique reference to user */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description User was deleted; also returned if user did not exist */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                403: components["responses"]["UnauthorizedError"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{id}/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Updates the password of an existing user
         * @description Updates the password of an existing user
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description unique reference to user */
                    id: string;
                };
                cookie?: never;
            };
            /** @description The password to be updated */
            requestBody: {
                content: {
                    "application/json": {
                        /**
                         * Format: password
                         * @example k9wPüä=kdHs2
                         */
                        password?: string;
                    };
                };
            };
            responses: {
                /** @description User sucessfully updated */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"];
                    };
                };
                403: components["responses"]["UnauthorizedError"];
                /** @description User (id) does not exist */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * calculate and fill database table with statistics
         * @description calculates the statistics for today +/- one month and stores them in database;
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Statistics have successfully been calculated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["StatsEntryResult"];
                    };
                };
                403: components["responses"]["UnauthorizedError"];
            };
        };
        post?: never;
        /** Deletes all entries from statistics table */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Statistics data have successfully been deleted */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * Format: int32
                             * @example 953
                             */
                            size?: number;
                        };
                    };
                };
                403: components["responses"]["UnauthorizedError"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stats/{date}/{timeUnit}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * calculate statistics (evtl. accumulated)
         * @description Returns the aggregated statistics for a given time day
         */
        get: {
            parameters: {
                query?: {
                    /** @description indicates if statistics are to be accumulated or just presented */
                    accumulate?: boolean;
                    /** @description indicates if the data should be filled with all days of this time range; if no measured value is available, the value is 0 */
                    fill?: boolean;
                };
                header?: never;
                path: {
                    /** @description timestamp representing a date */
                    date: number;
                    /** @description time unit */
                    timeUnit: "year" | "month" | "week" | "day";
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description statistics for the given date */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AggregatedStats"];
                    };
                };
                403: components["responses"]["UnauthorizedError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/statistics/aggregate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * calculate aggregated statistics
         * @description calculates statistics aggregated to the geven timeUnit
         */
        get: {
            parameters: {
                query: {
                    /** @description time unit */
                    timeUnit: "year" | "month" | "week" | "day";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description calculated aggregated statistics for this given timeUnit */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AggregatedStatistics"];
                    };
                };
                403: components["responses"]["UnauthorizedError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/statistics/histogram/{interval}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * calculate historgram from statistic data
         * @description returns a histogram with a given interval (time) and optionally filtered by direction (enter, go or both)
         */
        get: {
            parameters: {
                query?: {
                    /** @description filter entries by their direction */
                    direction?: "enter" | "go";
                };
                header?: never;
                path: {
                    /** @description time interval this historgram should be created */
                    interval: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description histogramm according to the given parameters */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * Format: date-time
                             * @example 1970-01-01T08:20:00.000Z
                             */
                            time?: string;
                            /** @example 512 */
                            histValue?: number;
                        }[];
                    };
                };
                403: components["responses"]["UnauthorizedError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/statistics/breaktime/{interval}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * calculate historgram of break times from statistic data
         * @description returns a histogram of break times optionally filtered by "real" measurement of breaks or, in case of only two entries this day, calculated default breaks (45 min).
         */
        get: {
            parameters: {
                query?: {
                    /** @description filter entries by their direction */
                    real?: boolean;
                };
                header?: never;
                path: {
                    /** @description time interval this historgram should be created */
                    interval: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description histogramm according to the given parameters */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example 40 */
                            time?: number;
                            /** @example 689 */
                            breaktime?: number;
                        }[];
                    };
                };
                403: components["responses"]["UnauthorizedError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/statistics/extrahours": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * calculate extra hours starting with Oct/2023
         * @description Returns the extra hours per day either as value or accumulated over time
         */
        get: {
            parameters: {
                query: {
                    /** @description indicates if statistics are to be accumulated or just presented */
                    accumulate: boolean;
                    /** @description time unit */
                    timeUnit: "year" | "month" | "week" | "day";
                    /**
                     * @description start date from which the calculation starts
                     * @example 2022-03-16T00:00:00.000Z
                     */
                    startDate?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Extra hours according to the given parameters */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: date */
                            date?: string;
                            /** @example 1.2 */
                            extra_hour?: number;
                        }[];
                    };
                };
                403: components["responses"]["UnauthorizedError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Version of this application
         * @description reveals the actual version of this application
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description version information regarding this application */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["VersionResp"];
                    };
                };
                403: components["responses"]["UnauthorizedError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/schedule": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * API to schedule jobs
         * @description Exposes an API to jobs trigger by an external scheduler (like kubernetes CronJob)
         */
        put: {
            parameters: {
                query: {
                    /** @description job class defines the job to be triggered */
                    jobclass: "CALC_STATS" | "DUMP_MODELS" | "BACKUP_TIME_ENTRIES" | "EVALUATE" | "REMOVE_TESTER_TOKEN" | "REMOVE_EXIRED_TOKEN" | "RESET_GEOFENCE_CHEKINS";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description job successfully triggered; please mind that it runs in the background and there is no error code in case it fails */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description job class invalid or not provided */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Healthcheck endpoint
         * @description Performs a healthcheck if this app (no auth required)
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Healthcheck was performed successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HealthcheckResp"];
                    };
                };
                /** @description Healthcheck could not be performed successfully because this or a dependend service was not available. */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/log": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Log request object
         * @description Logs several values of request to console of server
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description version information regarding this application */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LogResp"];
                    };
                };
            };
        };
        /**
         * Log request object
         * @description Logs several values of request to console of server
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description version information regarding this application */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LogResp"];
                    };
                };
            };
        };
        /**
         * Log request object
         * @description Logs several values of request to console of server
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description version information regarding this application */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LogResp"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        TimeEntry: {
            /**
             * Format: date-time
             * @description The date this time entry represents
             * @example 2000-01-01T10:15:02.151Z
             */
            entry_date: string;
            /**
             * Format: date-time
             * @description Date of last change on this time entry
             * @example 2000-01-01T10:15:02.151Z
             */
            last_changed?: string;
            /**
             * @description direction of this time entry; representing, if the time entry means a coming or going event:
             *      * `go` - leaving
             *      * `enter` - entering
             * @example enter
             * @enum {string}
             */
            direction: "enter" | "go";
            /**
             * @description the longitude geo coordinate
             * @example 10.875482
             */
            longitude?: number;
            /**
             * @description the latitude geo coordinate
             * @example 49.514135
             */
            latitude?: number;
        };
        Geofence: {
            /**
             * @description identifier of this geofence
             * @example 6367e7c3a94ff60017d7c1ce
             */
            id: string;
            /**
             * @description flag that indicates if the geo fence should trigger or not
             * @example true
             */
            enabled: boolean;
            /**
             * @description radius of the geofence within it matches
             * @example 150
             */
            radius: number;
            /**
             * @description the longitude geo coordinate
             * @example 10.875482
             */
            longitude: number;
            /**
             * @description the latitude geo coordinate
             * @example 49.514135
             */
            latitude: number;
            /**
             * @description A (unique) description of this geofence; name it after the location
             * @example Home
             */
            description: string;
            /**
             * @description flag that indicates if one is chacked in at this geofence
             * @example false
             */
            isCheckedIn: boolean;
            /**
             * Format: date
             * @description date of last checkin or checkout
             * @example 2020-07-15T10:45:23.000Z
             */
            lastChange: string;
        };
        Geofences: components["schemas"]["Geofence"][];
        Geotrack: {
            /**
             * @description the longitude geo coordinate
             * @example 10.875482
             */
            longitude?: number;
            /**
             * @description the latitude geo coordinate
             * @example 49.514135
             */
            latitude?: number;
            /**
             * @description the accuracy of the position measurement in meter (radius)
             * @example 60
             */
            accuracy?: number;
            /**
             * @description identifier of the sender of this request
             * @example HASSIO
             */
            source?: string;
            /**
             * @description the longitude geo coordinate
             * @example 10.875482
             */
            lon?: number;
            /**
             * @description the latitude geo coordinate
             * @example 49.514135
             */
            lat?: number;
            /**
             * @description the accuracy of the position measurement in meter (radius)
             * @example 60
             */
            acc?: number;
            /**
             * @description altitude of the position
             * @example 320
             */
            altitude?: number;
            /**
             * @description unix timestamp of this event
             * @example 1594913160
             */
            tst?: number;
            /** @description description (?) */
            desc?: string;
            /** @description some source identifier; sometimes its desc, sometimes its tid */
            tid?: string;
        };
        GeotrackResp: {
            /**
             * @description the longitude geo coordinate
             * @example 10.875482
             */
            longitude?: number;
            /**
             * @description the latitude geo coordinate
             * @example 49.514135
             */
            latitude?: number;
            /**
             * @description the accuracy of the position measurement in meter (radius)
             * @example 60
             */
            accuracy?: number;
            /**
             * @description the velocity in [m/s] between two points (this related to the last one in time)
             * @example 22.3
             */
            velocity?: number;
            /**
             * @description The time in [s] passed between two points (this related to the last one in time)
             * @example 11620
             */
            timediff?: number;
            /**
             * @description The distance in [m] passed between two points (this related to the last one in time)
             * @example 320
             */
            dist?: number;
            /**
             * @description identifier of the sender of this request
             * @example HASSIO
             */
            source?: string;
            /**
             * @description altitude of the position
             * @example 320
             */
            altitude?: number;
            /**
             * Format: date
             * @description date of this entry in ISO format
             * @example 2020-07-15T10:45:23.000Z
             */
            date?: string;
        };
        GeotrackResponses: components["schemas"]["GeotrackResp"][];
        GeotrackMetaDataResponse: {
            /**
             * @description number of geo track entries for the given time span
             * @example 210
             */
            size?: number;
            /**
             * @description distance in meter of the given time span
             * @example 21232
             */
            totalDistance?: number;
            accuracy?: {
                /**
                 * @description mean of accuracies in meters of all geo locations
                 * @example 114.232
                 */
                mean?: number;
                /**
                 * @description variance of accuracies in meters of all geo locations
                 * @example 11.031
                 */
                variance?: number;
            };
        };
        TimeEntries: components["schemas"]["TimeEntry"][];
        Toggle: {
            /** @example __TEST__ */
            name: string;
            /** @example false */
            toggle: string;
            /** @example some text */
            notification: string;
        };
        Toggles: components["schemas"]["Toggle"][];
        Property: {
            /** @example de.nobio.timetracker.KEY_01 */
            key: string;
            /** @example this is a value */
            value: string;
        };
        Properties: components["schemas"]["Property"][];
        StatsEntryResult: {
            firstEntry?: {
                /** @example 0 */
                _id?: number;
                /** @example 2014-01-13T06:30:00.000Z */
                age?: string;
            };
            lastEntry?: {
                /** @example 0 */
                _id?: number;
                /** @example 2019-01-10T21:13:29.233Z */
                age?: string;
            };
        };
        AggregatedStats: {
            chart_data?: {
                /** @enum {string} */
                yScale?: "linear";
                /** @enum {string} */
                xScale?: "ordinal" | "time";
                /** @enum {string} */
                type?: "bar" | "line-dottet";
                main?: {
                    data?: number[];
                };
                comp?: {
                    /** @enum {string} */
                    type?: "line";
                    data?: number[];
                };
            };
        };
        AggregatedStatistics: {
            chart_data?: {
                /** @enum {string} */
                yScale?: "linear";
                /** @enum {string} */
                xScale?: "ordinal" | "time";
                /** @enum {string} */
                type?: "bar" | "line-dottet";
                yMin?: number;
                main?: {
                    data?: {
                        y?: number;
                        x?: number;
                        n?: number;
                        dev?: string;
                    };
                };
                comp?: {
                    /** @enum {string} */
                    type?: "line";
                    data?: number[];
                };
            };
        };
        UniqueUsers: components["schemas"]["UniqueUser"][];
        UniqueUser: {
            /** @example asdjas0sd-sdasdi-asdasd */
            id?: string;
            /** @example tester */
            username?: string;
            /** @example Tester */
            name?: string;
            /** @example albert@einstein.edu */
            mailAddress?: string;
        };
        User: {
            /** @example tester */
            username: string;
            /** @example Tester */
            name: string;
            /** @example albert@einstein.edu */
            mailAddress: string;
        };
        FullUser: {
            /** @example Tester */
            username: string;
            /**
             * Format: password
             * @example jshHfu3ek=fDÖ
             */
            password: string;
            /** @example Tester */
            name?: string;
            /** @example albert@einstein.edu */
            mailAddress?: string;
        };
        Token: {
            /**
             * @description JWT
             * @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
             */
            token: string;
        };
        "Mark-a-Day": {
            /**
             * Format: date
             * @description The date this time entry represents; if not provided "today" will be used
             * @example 2000-01-01T10:15:02.151Z
             */
            entry_date?: string;
            /**
             * @description Marker that indicates the reason
             * @example sick-leave
             * @enum {string}
             */
            mark: "vacation" | "sick-leave";
        };
        VersionResp: {
            /**
             * @description version of this application
             * @example 11.2.3
             */
            version: string;
            /**
             * Format: date-time
             * @description date/time of last build
             * @example 2000-01-01T10:15:02.151Z
             */
            last_build: string;
        };
        HealthcheckResp: {
            /**
             * @description Status of healthcheck. “pass”: healthy “fail”: unhealthy “warn”: healthy, with some concerns
             * @example pass
             * @enum {string}
             */
            status?: "pass" | "fail" | "warn";
            /**
             * @description version of this application
             * @example 11.2.3
             */
            version?: string;
            /**
             * Format: date-time
             * @description date/time of this health check
             * @example 2000-01-01T10:15:02.151Z
             */
            time?: string;
            details?: {
                /**
                 * @description Name of this component
                 * @example database
                 */
                name?: string;
                /**
                 * @description Types of component.
                 * @enum {string}
                 */
                componentType?: "component" | "datastore" | "system";
                /**
                 * @description Unit of the measured metric value
                 * @enum {string}
                 */
                metricUnit?: "ms" | "s" | "percent" | "GiB" | "MiB";
                /** @description the value of the given metricUnit. Needs to be a common data type to hold all other data types; currently it consists of time and byte and percentage */
                metricValue?: string;
            }[];
        };
        LogResp: {
            /**
             * @description url of this method
             * @example /api/url
             */
            url?: string;
            /**
             * Format: date-time
             * @description the method of this request
             * @example 2000-01-01T10:15:02.151Z
             */
            method?: string;
            /**
             * Format: json
             * @description JSON object of headers for this request
             * @example {
             *       "host": "localhost:30000",
             *       "user-agent": "curl/7.71.1",
             *       "accept": "*\/*",
             *       "content-length": "41",
             *       "content-type": "application/x-www-form-urlencoded"
             *     }
             */
            headers?: Record<string, never>;
            /**
             * Format: json
             * @description JSON object of body for this request; optional - only when passed
             * @example {
             *       "key": "value"
             *     }
             */
            body?: Record<string, never>;
        };
    };
    responses: {
        /** @description Access token is missing or invalid; try to refresh your token */
        UnauthorizedError: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
