services:
  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  # timetracker-ui - the frontend
  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  timetracker-ui:
    container_name: timetracker-ui2
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    image: nobio/timetracker-ui2:latest
    environment:
      - NODE_ENV=production
    env_file:
      - path: .env
        required: true
    ports:
      - "3000:3000"
